---
- hosts: modulo
  become: true
  vars:
    certbot_auto_renew_user: root
    certbot_auto_renew_minute: 17
    certbot_auto_renew_hour: 4

  roles:
    - geerlingguy.certbot

  tasks:
    - apt_repository:
        repo: 'ppa:certbot/certbot'
    - name: Install Certbot Nginx plugin
      apt: pkg=python-certbot-nginx state=latest update_cache=true
