---
- hosts: modulo
  become: true
  tasks:
    - name: Install Nginx
      apt: pkg=nginx state=latest update_cache=true
      notify: nginx reload
    - name: Copy config
      copy: src=modulolotus.net dest=/etc/nginx/sites-available/ backup=yes
      notify: nginx reload
    - name: Create symlink
      file: src=/etc/nginx/sites-available/modulolotus.net dest=/etc/nginx/sites-enabled/modulolotus.net state=link
      notify: nginx reload

  handlers:
    - name: nginx reload
      service: name=nginx state=reloaded
